version: "3.9"

services:
  account-db:
    image: mysql:8.0.28
    container_name: account-db
    hostname: account-db
    ports:
      - "3307:3306"
    environment:
        - MYSQL_DATABASE=accounts
        - MYSQL_ROOT_PASSWORD=${MYSQL_ACCOUNTS_ROOT_PASS}
        - MYSQL_USER=${MYSQL_ACCOUNTS_USER}
        - MYSQL_PASSWORD=${MYSQL_ACCOUNTS_PASS}
    volumes:
      - account_db_volume:/var/lib/mysql

volumes:
  account_db_volume: { }
