
spring:
  application:
    name: account-service
  r2dbc:
    url: r2dbc:mysql://localhost:3307/accounts
    username: user
    password: abc123
#    pool:
#      initial-size: 100
#      max-size: 500
#      max-idle-time: 30m
#      validation-query: SELECT 1

  flyway:
    url: r2dbc:mysql://localhost:3307/accounts
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

