# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build

      - name: Export drawio files to png files
          uses: rlespinasse/drawio-export-action@v2
          with:
            path: .diagrams
            format: png
            transparent: false
            output: .github/assets/img
              
              - name: Get author and committer info from HEAD commit
                uses: rlespinasse/git-commit-data-action@v1.x
                if: github.ref == 'refs/heads/main'

              - name: Commit changed files
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                  commit_message: "docs: sync draw.io exported files"
                  commit_user_name: "${{ env.GIT_COMMIT_COMMITTER_NAME }}"
                  commit_user_email: "${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
                  commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"
                if: github.ref == 'refs/heads/main'